---
- name: Crear namespace
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Crear Namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: nombre-del-namespace
        state: present
